steps:
  # Step 1: Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'wordpress-deployment.yaml'
    timeout: '600s'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=wordpress-cluster'

options:
  logging: 'CLOUD_LOGGING_ONLY'
